config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 開発環境でメーラーを確認
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'top_page#top'
  get 'terms_of_service', to: 'top_page#terms_of_service'
  get 'privacy_policy', to: 'top_page#privacy_policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create destroy]
  resource :profile, only: %i[edit update]

  resources :campsites, only: %i[index show guidance] do
    collection do
      get :mypage
    end
    member do
      get :guidance
    end
    resources :reviews, only: %i[index create destroy]
  end
  resources :bookmarks, only: %i[create destroy]

  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :campsites
  end

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/models/campsite.rb
class Campsite < ApplicationRecord
  include JpPrefecture
  jp_prefecture :prefecture_code
  mount_uploader :image, CampsiteImageUploader

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :name, uniqueness: true, presence: true
  validates :address, uniqueness: true, presence: true
  validates :prefecture_code, presence: true

  # 評価の平均を算出
  def avg_score
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f
    end
  end

  # 評価の平均の百分率(CSSに適用する)
  def review_score_percentage
    if reviews.empty?
      0.0
    else
      reviews.average(:score).round(1).to_f * 100 / 5
    end
  end
end

app/controllers/admin/campsites_controller.rb
class Admin::CampsitesController < Admin::BaseController
  before_action :set_campsite, only: %i[show edit update destroy]

  def index
    @search = Campsite.ransack(params[:q])
    @campsites = @search.result(distinc: true).page(params[:page])
  end

  def new
    @campsite = Campsite.new
  end

  def create
    @campsite = Campsite.new(campsaite_params)
    if @campsite.save
      redirect_to admin_campsites_path(@campsite), success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @campsite.update(campsaite_params)
      redirect_to admin_campsite_path(@campsite),
                  success: t('defaults.message.updated', item: Campsite.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Campsite.model_name.human)
      render :edit
    end
  end

  def destroy
    if @campsite.destroy!
      redirect_to admin_campsites_path(@campsites),
                  success: t('defaults.message.deleted', item: Campsite.model_name.human)
    end
  end

  private

  def campsaite_params
    params.require(:campsite).permit(:name, :address, :prefecture_code, :access,
                                     :description, :period, :checkin, :checkout, :phone,
                                     :contact_link, :latitude, :longitude, :image, :image_cache)
  end

  def set_campsite
    @campsite = Campsite.find(params[:id])
  end
end

app/controllers/campsites_controller.rb
class CampsitesController < ApplicationController
  require 'open-uri'
  require 'json'

  skip_before_action :require_login, only: %i[index show guidance]
  before_action :set_campsite, :set_lat_long_name, only: %i[show guidance]
  before_action :set_key_openweather_map, :rakuten_tent_get, :rakuten_hotel_get, :rakuten_books_get, only: %i[guidance]

  def index
    @search = Campsite.ransack(params[:q])
    @campsites = @search.result(distinc: true).page(params[:page])
    @count = @campsites.total_count
  end

  def show
    @review = Review.new
    @reviews = @campsite.reviews.order(created_at: :desc)
  end

  def mypage
    @bookmark_campsites = current_user.bookmarks.order(created_at: :desc).map(&:campsite)
  end

  def guidance; end

  private

  def set_campsite
    @campsite = Campsite.find(params[:id])
  end

  def set_key_openweather_map
    gon.openweather_map_key = Rails.application.credentials.dig(:open_weather, :appid)
  end

  def set_lat_long_name
    gon.campsite_name = @campsite.name
    gon.latitude = @campsite.latitude
    gon.longitude = @campsite.longitude
    gon.address = @campsite.address
  end

  def rakuten_tent_get
    api_key = Rails.application.credentials.rakuten[:key]
    rakuten_tent_url = "https://app.rakuten.co.jp/services/api/IchibaItem/Ranking/20170628?format=json&genreId=302373&applicationId=#{api_key}"
    response_tent = URI.open(rakuten_tent_url)
    rakuten_tent = JSON.parse(response_tent.read)
    get_tent = []
    rakuten_tent['Items'].first(20).each do |tent|
      get_tent << {
        name: tent['Item']['itemName'],
        url: tent['Item']['itemUrl'],
        image_url: tent['Item']['smallImageUrls'][0]['imageUrl'],
        price: tent['Item']['itemPrice'],
        score: tent['Item']['reviewAverage'],
        count: tent['Item']['reviewCount']
      }
    end
    @tents = get_tent.sample(4)
  end

  def rakuten_hotel_get
    api_key = Rails.application.credentials.rakuten[:key]
    begin
      rakuten_hotel_url = "https://app.rakuten.co.jp/services/api/Travel/SimpleHotelSearch/20170426?format=json&datumType=1&latitude=#{@campsite.latitude}&longitude=#{@campsite.longitude}&applicationId=#{api_key}&searchRadius=3"
      response_hotel = URI.open(rakuten_hotel_url)
      rakuten_hotel = JSON.parse(response_hotel.read)
      count = rakuten_hotel['hotels'].length > 4 ? 4 : rakuten_hotel['hotels'].length
      get_hotel = []
      rakuten_hotel['hotels'].first(count).each do |hotel|
        get_hotel << {
          name: hotel['hotel'][0]['hotelBasicInfo']['hotelName'],
          url: hotel['hotel'][0]['hotelBasicInfo']['hotelInformationUrl'],
          image_url: hotel['hotel'][0]['hotelBasicInfo']['hotelImageUrl'],
          review: hotel['hotel'][0]['hotelBasicInfo']['reviewAverage'],
          review_count: hotel['hotel'][0]['hotelBasicInfo']['reviewCount'],
          address1: hotel['hotel'][0]['hotelBasicInfo']['address1'],
          address2: hotel['hotel'][0]['hotelBasicInfo']['address2']
        }
      end
      @hotels = get_hotel
    rescue StandardError
      @hotels = []
    end
  end

  def rakuten_books_get
    api_key = Rails.application.credentials.rakuten[:key]
    rakuten_books_url = "https://app.rakuten.co.jp/services/api/BooksTotal/Search/20170404?format=json&keyword=%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97&booksGenreId=001&applicationId=#{api_key}"
    response_books = URI.open(rakuten_books_url)
    rakuten_books = JSON.parse(response_books.read)
    get_book = []
    rakuten_books['Items'].first(20).each do |book|
      get_book << {
        name: book['Item']['title'],
        url: book['Item']['itemUrl'],
        image_url: book['Item']['mediumImageUrl'],
        price: book['Item']['itemPrice'],
        sales: book['Item']['salesDate'],
        publisher: book['Item']['publisherName']
      }
    end
    @books = get_book.sample(4)
  end
end

app/views/admin/campsites/_campsite.html.erb
<tr>
    <td>
        <%= campsite.id %>
    </td>
    <td>
    <%= link_to campsite.name, admin_campsite_path(campsite) %>
    </td>
    <td>
        <%= campsite.prefecture.name %>
    </td>
    <td>
        <%= campsite.address %>
    </td>
    <td>
        <%= campsite.checkin %>
    </td>
    <td>
        <%= campsite.checkout %>
    </td>
    <td>
        <%= link_to t('defaults.show'), admin_campsite_path(campsite), class:"btn btn-info" %>
        <%= link_to t('defaults.edit'), edit_admin_campsite_path(campsite), class:"btn btn-success" %>
        <%= link_to t('defaults.delete'), admin_campsite_path(campsite), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class:"btn btn-danger" %>
    </td>
</tr>

app/views/admin/campsites/_search_form.html.erb
<%= search_form_for @search, url: admin_campsites_path do |f| %>
    <div class="row">
        <div class="form-inline align-items-center mx-auto">
            <div class="col-auto">
              <%= f.search_field :name_or_address_or_description_cont, placeholder: t('defaults.search_word'), class:'form-control' %>
            </div>
            <div class="col-md-4 d-inline-block">
              <%= f.collection_select :prefecture_code_eq, JpPrefecture::Prefecture.all, :code, :name,
              { include_blank: '都道府県を選択' }, { class: 'form-control text-muted' } %>
            </div>
            <div class="col-auto">
              <%= f.submit t('defaults.search'), class:'btn btn-primary ml-3' %>
            </div>
        </div>
    </div>
<% end %>

app/views/admin/campsites/edit.html.erb
<% content_for(:title, @campsite.name) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @campsite, url: admin_campsite_path(@campsite), local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="text-right mb-3">
          <%= link_to t('defaults.index'), admin_campsites_path(@campsite), class:"btn btn-warning" %>
          <%= link_to t('defaults.show'), admin_campsite_path(@campsite), class:"btn btn-info" %>
        </div>
        <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :prefecture_code %>
        <%= f.text_field :prefecture_code, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :access %>
        <%= f.text_area :access, class: "form-control", rows: "4" %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", rows: "6" %>
    </div>
    <div class="form-group">
        <%= f.label :period %>
        <%= f.text_field :period, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :checkin %>
        <%= f.text_field :checkin, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :checkout %>
        <%= f.text_field :checkout, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :contact_link %>
        <%= f.text_field :contact_link, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :latitude %>
        <%= f.text_field :latitude, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :longitude %>
        <%= f.text_field :longitude, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, onchange: 'previewImage()', class: 'form-control mb-3', accept: 'image/*' %>
        <%= f.hidden_field :image_cache %>
        <%= image_tag @campsite.image_url, class: 'rounded mb-3', id: 'preview', width: '50%', height: '50%' %>
    </div>
        <%= f.submit class: 'btn btn-primary mb-3' %>
      <% end %>
    </div>
  </div>
</div>

<script>
window.previewImage = function() {
    const target = this.event.target;
    const file = target.files[0];
    const reader  = new FileReader();
    reader.onloadend = function () {
        const preview = document.querySelector("#preview")
        if(preview) {
            preview.src = reader.result;
        }
    }
    if (file) {
        reader.readAsDataURL(file);
    }
}
</script>

app/views/admin/campsites/index.html.erb
<% content_for(:title, t('.title'))  %>
<div class="container pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <!-- 検索フォーム -->
      <div>
        <%= render 'search_form' %>
      </div>
    </div>
  </div>
  <div class="text-right mb-3">
    <%= link_to t('defaults.new'), new_admin_campsite_path, class:"btn btn-dark" %>
  </div>

　<!-- キャンプ場一覧 -->
<div class="row">
<div class="col-md-12">
  <table class="table table-striped small">
    <thead>
    <tr>
      <th scope="col"><%= Campsite.human_attribute_name(:id) %></th>
      <th scope="col"><%= Campsite.human_attribute_name(:name) %></th>
      <th scope="col">都道府県</th>
      <th scope="col"><%= Campsite.human_attribute_name(:address) %></th>
      <th scope="col"><%= Campsite.human_attribute_name(:checkin) %></th>
      <th scope="col"><%= Campsite.human_attribute_name(:checkout) %></th>
    </tr>
    </thead>
    <tbody>
    <%= render @campsites %>
    </tbody>
  </table>
</div>
</div>
<div class="row">
<div class="col-md-12">
  <!-- ページネーション -->
  <%= paginate @campsites %>
</div>
</div>
</div>

app/views/admin/campsites/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @campsite, url: admin_campsites_path(@campsite), local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="text-right mb-3">
          <%= link_to t('defaults.index'), admin_campsites_path, class:"btn btn-warning" %>
        </div>
        <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :prefecture_code %>
        <%= f.text_field :prefecture_code, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :access %>
        <%= f.text_area :access, class: "form-control", rows: "4" %>
    </div>
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", rows: "6" %>
    </div>
    <div class="form-group">
        <%= f.label :period %>
        <%= f.text_field :period, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :checkin %>
        <%= f.text_field :checkin, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :checkout %>
        <%= f.text_field :checkout, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :contact_link %>
        <%= f.text_field :contact_link, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :latitude %>
        <%= f.text_field :latitude, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :longitude %>
        <%= f.text_field :longitude, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, onchange: 'previewImage()', class: 'form-control mb-4', accept: 'image/*' %>
      <%= f.hidden_field :image_cache %>
    </div>
    <div class='mt-5 text-center'>
    <%= image_tag @campsite.image_url,
                  class: 'rounded mb-2',
                  id: 'preview',
                  width: '50%', height: '50%' %>
    </div>
      <%= f.submit class: 'btn btn-primary mb-3' %>
      <% end %>
    </div>
  </div>
</div>

<script>
window.previewImage = function() {
    const target = this.event.target;
    const file = target.files[0];
    const reader  = new FileReader();
    reader.onloadend = function () {
        const preview = document.querySelector("#preview")
        if(preview) {
            preview.src = reader.result;
        }
    }
    if (file) {
        reader.readAsDataURL(file);
    }
}
</script>

app/views/admin/campsites/show.html.erb
<% content_for(:title, @campsite.name) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.index'), admin_campsites_path(@campsite), class:"btn btn-warning" %>
        <%= link_to t('defaults.edit'), edit_admin_campsite_path(@campsite), class:"btn btn-success" %>
        <%= link_to t('defaults.delete'), admin_campsite_path(@campsite), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class:"btn btn-danger" %>
      </div>
      <table class="table table-bordered bg-white">
        <tbody>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:id) %></th>
          <td><%= @campsite.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:name) %></th>
          <td>
            <%= @campsite.name %>
          </td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:prefecture_code) %></th>
          <td><%= @campsite.prefecture_code %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:address) %></th>
          <td><%= @campsite.address %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:access) %></th>
          <td><%= @campsite.access %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:period) %></th>
          <td><%= @campsite.period %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:description) %></th>
          <td><%= @campsite.description %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:checkin) %></th>
          <td><%= @campsite.checkin %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:checkout) %></th>
          <td><%= @campsite.checkout %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:phone) %></th>
          <td><%= @campsite.phone %></td>
        </tr>
        <tr style="white-space: nowrap;">
          <th scope="row"><%= Campsite.human_attribute_name(:contact_link) %></th>
          <td><%= @campsite.contact_link %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:latitude) %></th>
          <td><%= @campsite.latitude %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:longitude) %></th>
          <td><%= @campsite.longitude %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:created_at) %></th>
          <td><%= l @campsite.created_at, format: :long %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:updated_at) %></th>
          <td><%= l @campsite.updated_at, format: :long %></td>
        </tr>
        <tr>
          <th scope="row"><%= Campsite.human_attribute_name(:image) %></th>
          <td><%= image_tag @campsite.image_url, class: 'rounded mb-3', width: '30%', height: '30%' %></td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>