config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 開発環境でメーラーを確認
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'top_page#top'
  get 'terms_of_service', to: 'top_page#terms_of_service'
  get 'privacy_policy', to: 'top_page#privacy_policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create destroy]
  resource :profile, only: %i[edit update]

  resources :campsites, only: %i[index show guidance] do
    collection do
      get :mypage
    end
    member do
      get :guidance
    end
    resources :reviews, only: %i[index create destroy]
  end
  resources :bookmarks, only: %i[create destroy]

  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :campsites
  end

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light" id="mainNav">
    <div class="container px-lg-5 mt-1">
      <%= link_to image_tag('logo.png'), root_path, 'data-turbolinks': false %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to campsites_path, class: "nav-link mr-3 small navbar-color" do %>
              <i class="fas fa-campground"></i> キャンプ場一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to new_user_path, class: "nav-link mr-3 small navbar-color" do %>
              <i class="fas fa-sign-in-alt"></i> 新規登録
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to login_path, class: "nav-link small navbar-color" do %>
              <i class="fas fa-user"></i> ログイン
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li style="list-style: none;"><%= msg %><button type="button" class="close" data-dismiss="alert">&times;</button></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div id="flash" class="flash-message container alert alert-<%= message_type %>">
    <i class="fas fa-check-circle"> </i>
    <%= message %><button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer">
  <section class="primary">
  <div class="mb-4">
    <%= link_to image_tag('logo-white.png'), root_path %>
  </div>
    <p class="discription">
    全国の<b>無料キャンプ場</b>を検索できて、周辺施設や天気を案内するサービス
    </p>
    <div class="navi-row">
      <ul class="navi">
        <li><%= link_to terms_of_service_path do %>利用規約<% end %></li>
        <li><%= link_to privacy_policy_path do %>プライバシーポリシー<% end %></li>
        <li><a href="https://docs.google.com/forms/d/e/1FAIpQLScWBUylYqqhGnD3ZNduB7uwRZxB1_oGv_qYXD5jhSVjyNFZkw/viewform" target="_blank" rel="noopener noreferrer">お問合わせ</a></li>
        <!-- <li><%= link_to '#' do %>キャンプマナー<% end %></li> -->
      </ul>
      <ul class="sns-navi">
        <!-- Twitter Share -->
        <li><%= link_to "https://twitter.com/share?&url=https://www.camphood.net/&text=%0D%0A全国の無料キャンプ場を検索できて、周辺施設や天気を案内するサービス CAMPHOOD&hashtags=無料キャンプ場,キャンプ,camp,個人開発&lang=ja",
        title: 'Twitter', target: :_blank, rel: 'noopener noreferrer' do %>
        <i class="fab fa-twitter"></i><% end %></li>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        <!-- Facebook Share -->
        <li><a href="https://www.facebook.com/share.php?u=https://www.camphood.net/" target="_blank" rel="noopener noreferrer"><i class="fab fa-facebook"></i></a></li>
        <!-- LINE Share -->
        <li><a href="https://line.me/R/msg/text/?https://www.camphood.net/" target="_blank" rel="nofollow noopener noreferrer"><i class="fab fa-line"></i></a></li>
      </ul>
    </div>
  </section>
  <section class="secondary">
    <p class="copyright">Copyright &copy; CAMPHOOD 2021. All rights reserved.</p>
  </section>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light" id="mainNav">
    <div class="container px-lg-5 mt-1">
      <%= link_to image_tag('logo.png'), root_path, class: 'logo', 'data-turbolinks': false %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to campsites_path, class: "nav-link mr-3 small navbar-color" do %>
              <i class="fas fa-campground"></i> キャンプ場一覧
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to mypage_campsites_path, class: "nav-link mr-3 small navbar-color" do %>
              <i class="fas fa-list"></i>
              <!--<%= image_tag current_user.avatar.url, class: "rounded-circle mb-2 ml-1", size: "25x25" %>-->
              マイページ
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to logout_path, method: :delete, data: { confirm: t('defaults.message.logout') }, class: "nav-link small navbar-color" do %>
              <i class="fas fa-user"></i> ログアウト
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_search_form.html.erb
<%= search_form_for search, url: url do |f| %>
  <div class="input-group mt-2 justify-content-center">
    <div class="col-sm-4">
      <%= f.collection_select :prefecture_code_eq, JpPrefecture::Prefecture.all, :code, :name,
      { include_blank: '都道府県を選択' }, { class: 'form-control text-muted custom-select' } %>
    </div>
  </div>
  <div class="col-auto d-inline-block">
    <%= f.button :type => "submit", :class =>"btn btn-success btn-s-md" do %>
    <i class="fa fa-search px-3"></i>
    <% end %>
  </div>
<% end %>

app/views/shared/_search_form_index.html.erb
<%= search_form_for search, url: url do |f| %>
  <div class="input-group justify-content-center">
    <div class="col-md-4 d-inline-block">
      <%= f.search_field :name_or_address_or_description_or_access_cont, class: 'form-control shadow mb-2', placeholder: "検索ワードを入力" %>
    </div>
    <div class="col-md-4 d-inline-block">
      <%= f.collection_select :prefecture_code_eq, JpPrefecture::Prefecture.all, :code, :name,
      { include_blank: '都道府県を選択' }, { class: 'form-control text-muted shadow custom-select mb-2' } %>
    </div>
    <div class="col-auto d-inline-block mb-2">
      <%= f.button :type => "submit", :class =>"btn btn-success btn-s-md" do %>
      <i class="fa fa-search px-2"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_search_form_mypage.html.erb
<%= search_form_for search, url: url do |f| %>
  <div class="input-group mt-4 mb-3 justify-content-center">
    <div class="col-md-4 d-inline-block">
      <%= f.search_field :name_or_address_or_description_or_access_cont, class: 'form-control shadow mb-2', placeholder: "お気に入り内を検索" %>
    </div>
    <div class="col-md-4 d-inline-block">
      <%= f.collection_select :prefecture_code_eq, JpPrefecture::Prefecture.all, :code, :name,
      { include_blank: '都道府県を選択' }, { class: 'form-control text-muted shadow custom-select mb-2' } %>
    </div>
    <div class="col-auto d-inline-block">
      <%= f.button :type => "submit", :class =>"btn btn-success btn-s-md" do %>
      <i class="fa fa-search px-2"></i>
      <% end %>
  </div>
<% end %>