config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 開発環境でメーラーを確認
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'top_page#top'
  get 'terms_of_service', to: 'top_page#terms_of_service'
  get 'privacy_policy', to: 'top_page#privacy_policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create destroy]
  resource :profile, only: %i[edit update]

  resources :campsites, only: %i[index show guidance] do
    collection do
      get :mypage
    end
    member do
      get :guidance
    end
    resources :reviews, only: %i[index create destroy]
  end
  resources :bookmarks, only: %i[create destroy]

  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :campsites
  end

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_campsites, through: :bookmarks, source: :campsite
  has_many :reviews, dependent: :destroy

  accepts_nested_attributes_for :authentications
  mount_uploader :avatar, AvatarUploader

  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, uniqueness: true, presence: true
  # uniqueness: { case_sensitive: true }とすると
  # RspecでUniqueness validator will no longer enforce case sensitive comparison in Rails 6.1警告がでない
  validates :reset_password_token, uniqueness: true, allow_nil: true

  enum role: { general: 0, admin: 1 }

  def bookmark(campsite)
    bookmark_campsites << campsite
  end

  def unbookmark(campsite)
    bookmark_campsites.destroy(campsite)
  end

  def bookmark?(campsite)
    bookmark_campsites.include?(campsite)
  end

  def own?(object)
    id == object.user_id
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @search = User.ransack(params[:q])
    @users = @search.result(distinc: true).order(created_at: :desc).page(params[:page])
  end

  def show; end

  def edit; end

  def update
    if @user.update(update_params)
      redirect_to admin_user_path(@user), success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to admin_users_path, success: t('defaults.message.deleted', item: User.model_name.human)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def update_params
    params.require(:user).permit(:email, :name, :avatar, :avatar_cache, :role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: t('.success')
      UserMailer.with(to: @user.email, name: @user.name).welcome.deliver_now
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    @user = User.find(current_user.id)
    @user.destroy!
    redirect_to root_path, danger: t('defaults.message.quited')
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/views/admin/users/_search_form.html.erb
<%= search_form_for @search, url: admin_users_path do |f| %>
    <div class="row">
        <div class="form-inline align-items-center mx-auto">
            <div class="col-auto">
              <%= f.search_field :name_cont, placeholder: t('defaults.search_word'), class:'form-control' %>
            </div>
            <div class="col-auto">
              <%= f.select :role_eq, User.roles_i18n.invert.map{|key, value| [key, User.roles[value]]}, { include_blank: t('defaults.unspecified') }, { class: 'form-control mr-1' } %>
            </div>
            <div class="col-auto">
              <%= f.submit t('defaults.search'), class:'btn btn-primary' %>
            </div>
        </div>
    </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
    <td>
        <%= user.id %>
    </td>
    <td>
        <%= link_to user.name, admin_user_path(user) %>
    </td>
    <td>
        <%= user.role_i18n %>
    </td>
    <td>
        <%= l user.created_at, format: :long %>
    </td>
    <td>
        <%= l user.updated_at, format: :long %>
    </td>
    <td>
        <%= link_to t('defaults.show'), admin_user_path(user), class:"btn btn-info" %>
        <%= link_to t('defaults.edit'), edit_admin_user_path(user), class:"btn btn-success" %>
        <%= link_to t('defaults.delete'), admin_user_path(user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class:"btn btn-danger" %>
    </td>
</tr>

app/views/admin/users/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="text-right mb-3">
          <%= link_to t('defaults.index'), admin_users_path(@user), class: 'btn btn-warning' %>
          <%= link_to t('defaults.show'), admin_user_path(@user), class: 'btn btn-info' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control mb-3' %>
        </div>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control mb-3' %>
        </div>

        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, onchange: 'previewFileWithId(preview)', class: 'form-control mb-3', accept: 'image/*' %>
          <%= f.hidden_field :avatar_cache %>
        </div>

            <div class='mt-3 mb-3'>
            <%= image_tag @user.avatar.url,
                            class: 'rounded-circle',
                            id: 'preview',
                            size: '100x100' %>
            </div>

        <div class="form-group">
          <%= f.label :role %>
          <%= f.select :role, User.roles_i18n.invert, {}, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% content_for(:title, t('.title'))  %>
<div class="container pt-2">
<h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <!-- 検索フォーム -->
      <%= render 'search_form' %>
    </div>
  </div>
　<!-- 掲示板一覧 -->
<div class="row">
<div class="col-md-12 small">
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col"><%= User.human_attribute_name(:id) %></th>
      <th scope="col"><%= User.human_attribute_name(:name) %></th>
      <th scope="col"><%= User.human_attribute_name(:role) %></th>
      <th scope="col"><%= User.human_attribute_name(:created_at) %></th>
      <th scope="col"><%= User.human_attribute_name(:updated_at) %></th>
    </tr>
    </thead>
    <tbody>
    <%= render @users %>
    </tbody>
  </table>
</div>
</div>
<div class="row">
<div class="col-md-12">
  <!-- ページネーション -->
  <%= paginate @users %>
</div>
</div>
</div>

app/views/admin/users/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.index'), admin_users_path(@user), class: 'btn btn-warning' %>
        <%= link_to t('defaults.edit'), edit_admin_user_path(@user), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admin_user_path(@user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= User.human_attribute_name(:id) %></th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:role) %></th>
          <td><%= @user.role_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:name) %></th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:email) %></th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:avatar) %></th>
          <td><%= image_tag @user.avatar.url, class: 'rounded', width: '50%', height: '50%' %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:created_at) %></th>
          <td><%= l @user.created_at, format: :long %></td>
        </tr>
                <tr>
          <th scope="row"><%= User.human_attribute_name(:updated_at) %></th>
          <td><%= l @user.updated_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>