config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # 開発環境でメーラーを確認
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'top_page#top'
  get 'terms_of_service', to: 'top_page#terms_of_service'
  get 'privacy_policy', to: 'top_page#privacy_policy'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create destroy]
  resource :profile, only: %i[edit update]

  resources :campsites, only: %i[index show guidance] do
    collection do
      get :mypage
    end
    member do
      get :guidance
    end
    resources :reviews, only: %i[index create destroy]
  end
  resources :bookmarks, only: %i[create destroy]

  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index show edit update destroy]
    resources :campsites
  end

  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::BaseController
  skip_before_action :require_login, only: %i[new create]
  skip_before_action :check_admin, only: %i[new create]
  layout 'layouts/admin_login'

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_to admin_root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to admin_login_path, success: t('.success')
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_back_or_to root_path, danger: t('.success')
  end
end

app/views/user_sessions/new.html.erb
<% content_for(:title, t('.title')) %>
<%# <% breadcrumb :login %>
<div id="login" class="container">
  <div class="row">
    <div class="col col-md-10 offset-md-1 col-lg-8 offset-lg-2 mt-3">
      <%= form_with url: login_path, local: true, class: 'login-form mt-3' do |f| %>
        <p class="login-text">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-lock fa-stack-1x"></i>
          </span>
        </p>
        <div class="form-group col-xs-12">
          <%= f.email_field :email, class: 'login-username fa small', placeholder: "\uf0e0 Email", autofocus: 'true', required: 'true', id: 'emailfield' %>
        </div>
        <div class="form-group col-xs-12">
          <%= f.password_field :password, class: 'login-password fa small', placeholder: "\uf084 Password", required: 'true', id: 'passwordfield' %>
          <%= link_to (t '.password_forget'), new_password_reset_path, class: 'text-muted small' %>
        </div>
        <%= f.submit (t 'defaults.login'), class: 'login-submit px-3 mt-4' %>
      <% end %>
      <div class='text-center small mt-3'>
        <%= link_to (t '.to_register_page'), new_user_path, class: 'text-white' %>
      </div>
      <div class='text-center mt-5'>
        <%= link_to auth_at_provider_path(provider: :facebook), class: 'btn btn-primary text-white px-4' do %>
        <i class="fa fab fa-facebook-f"> Facebookでログイン</i>
        <% end %>
      </div>
      <div class="underlay-photo"></div>
      <div class="underlay-black"></div>
    </div>
  </div>
</div>